#see: https://jupyterbook.org/publish/gh-pages.html
name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    paths:
    - libro_optimizacion/temas/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    # Build the book
    - name: Build the book
      run: cd libro_optimizacion/temas && mkdir _build && chmod gou+wrx -R _build && docker run -v $(pwd):/datos --entrypoint "/home/myuser/.local/bin/jb" --rm palmoreck/jupyterlab_optimizacion_2:3.4.3 build /datos/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: libro_optimizacion/temas/_build/html

